### ISSUE TITLE
EPIC 228789925 (Lightning McQueen)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#1]
[228789925 - 9 - SG - Echelle.pdf](https://github.com/user-attachments/files/17279020/228789925.-.9.-.SG.-.Echelle.pdf)
[228789925 - 9 - SG - Mode ID.pdf](https://github.com/user-attachments/files/17279021/228789925.-.9.-.SG.-.Mode.ID.pdf)
[228789925 - 9 - SG - Peakbagged Echelle.pdf](https://github.com/user-attachments/files/17279022/228789925.-.9.-.SG.-.Peakbagged.Echelle.pdf)
[228789925 - 9 - SG - Peakbagging.pdf](https://github.com/user-attachments/files/17279023/228789925.-.9.-.SG.-.Peakbagging.pdf)

@nielsenmb @grd349
Any improvements to make?

**Comment by nielsenmb** [comment]
This one looks good to me!

Is there a way to show the figures directly in the issue? I think there should be. Maybe if it's a png instead.

**Comment by grd349** [comment]
Are at all worried that we have missed modes at high-frequency?  I'm not sure it's easy for me to see given the current plots.  Are we able to modify the plots to include extra frequency space?  Perhaps an additional plot?

**Comment by nielsenmb** [comment]
You can make the echelle of the residual. It's not something I built in yet, but it should probably be done. It's a good way to spot missing modes for sub-giants with lots of mixed modes. The current format with solutions overplotted can become very confusing to look at. 

That said we should probably also come up with a way to recycle a known, good, solution and expand the search to higher/lower frequencies. It's going to be relevant for plato too.

**Comment by George-Hookway** [comment]
This was the highest number of modes before the lower frequency modes became too smudged.

![228789925 - 10 - SG - Echelle](https://github.com/user-attachments/assets/ad53f889-e6f5-42bf-8f55-e4ae318932c2)
![228789925 - 10 - SG - Mode ID](https://github.com/user-attachments/assets/d107d153-f5f2-43fc-922d-0a91408f5f47)
![228789925 - 10 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/00c1242b-fe17-4d96-be08-c0988ea02cf3)
![228789925 - 10 - SG - Peakbagging](https://github.com/user-attachments/assets/8145960b-e802-4770-a4f6-607de2c8bd66)

**Comment by grd349** [comment]
@nielsenmb should we try and make numax higher?  Perhaps to help capture more high-frequency modes.

**Comment by nielsenmb** [comment]
Not sure that would make much of a difference, unless you increase it a lot. Again, PBjam only uses numax to define the prior sample, so if you just bump it up by ~10-50 muHz, you're probably not going to change the prior significantly, so you'll just get the same numax. 

I think the only option is increasing Np, but it'll always be centered on numax, so you're going to get more modes in the model below numax too, and I think @George-Hookway  has already tried this?

**Comment by George-Hookway** [comment]
Indeed. When I increased Np beyond 10, it managed to successfully find higher frequency modes, though at the sacrifice of the precision and correctness of the lower modes. Since the lower modes are more important to find, I felt this was the optimum situation.

If we could keep the lower frequency modes fixed and then search for higher frequency modes, this would be ideal. However, until this is possible, I feel this is the best result we'll get for this star.

**Comment by grd349** [comment]
Interesting - we should discuss on Friday.

**Comment by grd349** [comment]
Are we sure we are happy with this one?

**Comment by George-Hookway** [comment]
The only way to improve it that I can see is to add a feature to PBjam where it can keep certain mode IDs fixed and then look for others. Without that the lower frequency modes lose precision, and these are the more important ones

**Comment by grd349** [comment]
OK - Good to know.  We shall discuss this!
