### ISSUE TITLE
EPIC 211401787 (Patrick)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#10]
![211401787 - 14 - MS - Echelle](https://github.com/user-attachments/assets/9e3262b0-2c7c-4fd0-a1a8-abe47ab96c39)
![211401787 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/0abf7770-e670-49f6-b276-05de4fef44ee)
![211401787 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/08f25d8f-046f-4a2e-ac9f-0d4de3bef6ac)
![211401787 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/a21fbb03-991f-44d0-b5bd-8633cf19ccad)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
F-type star, but epsilon looks sensible so I think it's fine.

**Comment by grd349** [comment]
I think we need to discuss this one.

**Comment by nielsenmb** [comment]
Looks alright, but what is the epsilon value out of curiosity?

**Comment by George-Hookway** [comment]
PBjam used 0.985, where my model suggested 1.065

**Comment by nielsenmb** [comment]
Yeah, it looks like a late F-type star to me, so an epsilon around ~1 sounds correct.

**Comment by George-Hookway** [comment]
![211401787 - 10 - MS - Echelle](https://github.com/user-attachments/assets/85c7106e-4f14-41c6-b668-94a386921e34)
![211401787 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/168511cf-560a-4b10-a167-209ffd963f0d)
![211401787 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/7f79ed1c-3422-4aa5-ab5b-fbc921af93a2)
![211401787 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/0657a56b-36dc-4a35-a13a-c6c547cd29b8)

**Comment by grd349** [comment]
Yeah - I think so.
