### ISSUE TITLE
EPIC 228837389 (Hatchling)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#101]
![228837389 - 10 - SG - Echelle](https://github.com/user-attachments/assets/895dfe6a-e320-478f-8cd3-d2daf497b60e)
![228837389 - 10 - SG - Mode ID](https://github.com/user-attachments/assets/c8e35c8f-c910-4a07-98bc-ce7057800c30)
![228837389 - 10 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/77053bd5-fef6-4665-8a1e-0fd60b70a256)
![228837389 - 10 - SG - Peakbagging](https://github.com/user-attachments/assets/2281e772-0fb7-4aea-828c-af212b92f787)

@nielsenmb @grd349

**Comment by grd349** [comment]
Did it miss a low-frequency peak?

**Comment by George-Hookway** [comment]
The one at 400?

**Comment by nielsenmb** [comment]
Not sure about this one, it catches a lot of modes but I'm not 100% sure if it's missing a lot and/or putting in a lot where they shouldn't be.

**Comment by George-Hookway** [comment]
A hint of dodgy
