### ISSUE TITLE
EPIC 248855475 (Romana)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#104]
![248855475 - 10 - SG - Echelle](https://github.com/user-attachments/assets/e8606fdf-cd7f-4d52-bb91-4652678c586e)
![248855475 - 10 - SG - Mode ID](https://github.com/user-attachments/assets/a7cc4ca8-6b37-4a38-acbe-30fc6a6a562d)
![248855475 - 10 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/1b2e1533-7a26-414c-a873-493d2e5c9cfc)
![248855475 - 10 - SG - Peakbagging](https://github.com/user-attachments/assets/9d85f168-e23b-4e6c-a5dc-b1ab7ca2cec7)

@nielsenmb @grd349

**Comment by grd349** [comment]
Good for me!

**Comment by nielsenmb** [comment]
There are a lot more g-modes than usual for this numax, which is probably caused by an unusually low Teff. Could it be wrong? Or is there some stellar modeling shenanigans that can explain this?

The solution looks good, but I'm just wondering if the same solution can be found using a higher DPi1,

**Comment by grd349** [comment]
Yeah - i think the end result looks ok here.  

For the period spacing question - we could consider running BASTA and seeing what comes out.

**Comment by nielsenmb** [comment]
George had an HR diagram and it sits far to the right below the RGB at ~5000K. It kind of tracks with the very narrow linewidths, but I've just never seen such a high numax for such a cool star.
