### ISSUE TITLE
EPIC 237799552 (Zini)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#105]
![237799552 - 14 - MS - Echelle](https://github.com/user-attachments/assets/134195a1-bbe0-477d-9e33-d6ad875526d3)
![237799552 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/b973cb70-7383-4614-b67b-41279032e231)
![237799552 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/a10e70e6-25c4-4960-90c7-a85d670ccc42)
![237799552 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/bae91629-6d5d-46cd-ac9e-7d31df886e0a)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Almost as if the l=2,0 ridge is off by d02??

**Comment by George-Hookway** [comment]
![image](https://github.com/user-attachments/assets/15588ac9-43b5-4db0-bb24-009fc4213744)

I thought at one point that this could be a binary, but it looks more like noise now

**Comment by George-Hookway** [comment]
> Almost as if the l=2,0 ridge is off by d02??

It does look like the l=2 ridge is more prominent than the l=0

**Comment by grd349** [comment]
Another one to look at closely - not sure what is happening here.
