### ISSUE TITLE
EPIC 219179379 (The Hourglass Twins)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#107]
![219179379 - 16 - MS - Echelle](https://github.com/user-attachments/assets/e7f62773-03a0-46f0-9204-c8975410fe8a)
![219179379 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/05c0d75d-272f-41ac-a974-cbe6c4a27bf0)
![219179379 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/b84312b5-206d-4ad7-89eb-0a1126422cfc)
![219179379 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/dbb822b2-b758-423d-b475-3750f3d02e7a)

@nielsenmb @grd349

**Comment by grd349** [comment]
Do we know what the low-frequency peaks are?

**Comment by nielsenmb** [comment]
Considering the proximity in frequency to the main envelope, I think I would expect to see the slanted ridges in the echelle if they were equally spaced, similar to what we saw for Merry and Pippin.

**Comment by George-Hookway** [comment]
Right, so because their numaxs are so similar, they would have a similar dnu, which would mean it should still be visible on the echelle plot

**Comment by George-Hookway** [comment]
Treated as single star
