### ISSUE TITLE
EPIC 248687497 (Rod)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#108]
![248687497 - 14 - MS - Echelle](https://github.com/user-attachments/assets/2efa3f16-134b-4f2a-8419-e92499743210)
![248687497 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/a556facd-2f38-4c2a-bbee-74a4864f0d33)
![248687497 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/e5d9fcb1-3e2c-4126-b834-28e630087913)
![248687497 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/5e8d0464-1445-4e7d-a85b-11f9479525be)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
There was a baddie that I had to remove, but now it has a good result

**Comment by nielsenmb** [comment]
Nice!

**Comment by grd349** [comment]
Agreed!
