### ISSUE TITLE
EPIC 249580606 (Kate)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#109]
![249580606 - 14 - MS - Echelle](https://github.com/user-attachments/assets/99b283cb-167e-483b-833a-5c6869480911)
![249580606 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/21d1fa75-4f33-4769-bb01-aed8d7ef9a62)
![249580606 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/92677aa6-e9fe-49f6-bd42-8cce3d44db98)
![249580606 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/a0762a9e-276c-4cac-a26b-f1f72ec4d92d)

@nielsenmb @grd349

**Comment by grd349** [comment]
Lovely!

**Comment by nielsenmb** [comment]
An l=3 sneaking in there?

Looks good!
