### ISSUE TITLE
EPIC 212617037 (Jon)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#11]
![212617037 - 14 - MS - Echelle](https://github.com/user-attachments/assets/8d3ebb7e-2fa0-4367-81d9-a6f2af61b5bf)
![212617037 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/23ae6022-dfcb-4907-b3aa-b71911001dd4)
![212617037 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c20f2c97-8aab-4595-a969-ce3da5f8ab30)
![212617037 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/0ea38f98-9dbd-409b-b382-80365995a94f)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Keystone numax is ~880, which looks slightly low. Though if I'm right in thinking that lower frequency modes are harder to observe, this should be expected.

**Comment by grd349** [comment]
Let's talk about this one.

**Comment by nielsenmb** [comment]
numax for F-stars is harder since the envelope is usually wide and flat, so I'm not surprised if there are differences in numax. This is one where we might have to rely on the epsilon_p value to say whether or not the mode ID is correct. I can't really see any clear distinction between the modes in the spectrum, and the scatter in the samples in the echelles is too large to tell there as well.

**Comment by George-Hookway** [comment]
PBjam used an epsilon of 0.75, and the rough model I made suggests 0.90. I was thinking that these values are close enough for it to be believed, as it would have to be off my ~0.5 for there to be a concern.

**Comment by nielsenmb** [comment]
That sounds fine to me then, dnu looks good, numax looks good, so it's probably a good mode ID then.

**Comment by George-Hookway** [comment]
This was a potential binary for the NOT survey, if my remember serves.

**Comment by nielsenmb** [comment]
Quite a lot of curvature, but the end result looks OK?

**Comment by nielsenmb** [comment]
I suppose, if it puts numax right in the middle, and tries to find a dnu that is exactly halfway between the two, the one ridge would slant one way, and the other the other way. The chances of that happening though...

**Comment by George-Hookway** [comment]
By eye, difficult. Should be fine. Will check later
