### ISSUE TITLE
EPIC 248553904 (Tony)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#110]
![248553904 - 10 - MS - Echelle](https://github.com/user-attachments/assets/7ba10cb4-96c9-4a72-994f-ab407c88f860)
![248553904 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/7865f50a-862f-4ef1-aee3-023868fcaed2)
![248553904 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/92b3f6b4-884b-4414-b9d9-52cb66c92430)
![248553904 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/7a0d89f1-9875-40a4-9f5e-d3a7ec6df577)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks alright to me.

**Comment by grd349** [comment]
Approved
