### ISSUE TITLE
EPIC 249549448 (Margaret the Slitheen)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#111]
![249549448 - 10 - MS - Echelle](https://github.com/user-attachments/assets/0ca9eeab-4a8b-4bd2-bc72-b8de92b5ced5)
![249549448 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/4a1af2d6-5e0f-42b4-8de0-f7dca29e2d88)
![249549448 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/0c8dd49b-933f-4cca-aafc-f072c18b9a2b)
![249549448 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/07859c82-3e4b-4266-a961-efc7dbcb4227)

@nielsenmb @grd349

**Comment by grd349** [comment]
Yes 👍
