### ISSUE TITLE
EPIC 212340257 (Boba Fett)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#112]

**Comment by George-Hookway** [comment]
![212340257 - 8 - MS - Echelle](https://github.com/user-attachments/assets/078cf35a-b81c-4f8f-9705-ecde9d46e98b)
![212340257 - 8 - MS - Mode ID](https://github.com/user-attachments/assets/f142b8b1-c3ae-4136-98a5-4fad0ea171b4)
![212340257 - 8 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/cd428daf-abc5-4510-a66c-631e744376d3)
![212340257 - 8 - MS - Peakbagging](https://github.com/user-attachments/assets/2f8c5a6b-8b13-4aec-8668-3eedd21e23a3)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
I think it's a classic case of, if epsilon fits then it's probably OK. Dnu looks spot on.

**Comment by grd349** [comment]
Look good enough to me, and I assume that it is cool ~56/5700K and so epsilon looks ok.

**Comment by nielsenmb** [comment]
Hmm 0.1 is quite a bit actually, remember the range for main sequence stars isn't enormous.

**Comment by George-Hookway** [comment]
![White et al  2012](https://github.com/user-attachments/assets/6456042f-e136-42ce-ae00-462d813609e0)

**Comment by George-Hookway** [comment]
This was a plot from White et al. (2012), and the range of epsilons for a single temperature is quite high. I was using the method of if it was greater than 0.15 off, then I would investigate

**Comment by nielsenmb** [comment]
OK, that looks fine to me.
