### ISSUE TITLE
EPIC 248825038 (Rory)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#114]
![248825038 - 12 - MS - Echelle](https://github.com/user-attachments/assets/87c882a1-f93c-47a2-b253-c4e2e4c678bc)
![248825038 - 12 - MS - Mode ID](https://github.com/user-attachments/assets/bcd0df45-6c56-4de5-aa09-ae01193578ea)
![248825038 - 12 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/319e5c1c-8196-4139-9f31-7700142918f9)
![248825038 - 12 - MS - Peakbagging](https://github.com/user-attachments/assets/fe6c70b6-6532-432e-bd2e-af923412e08f)

@nielsenmb @grd349

**Comment by grd349** [comment]
Lovely - are there more orders at high-frequency?

**Comment by George-Hookway** [comment]
> Lovely - are there more orders at high-frequency?

I would say no, as they seem to go against the curvature, at least when looking at the echelle plot. But I'll see what comes out.

**Comment by George-Hookway** [comment]
![248825038 - 13 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/f4f84d9e-8200-4748-93b2-ded600c4772a)

**Comment by George-Hookway** [comment]
There was nothing of note there, so I'll tick this one off.
