### ISSUE TITLE
EPIC 228720824 (Shakespeare)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#116]
![228720824 - 10 - MS - Echelle](https://github.com/user-attachments/assets/9b5214ab-a762-4aa7-9e6f-4783b1b05007)
![228720824 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/89d89c05-c7e2-4161-a7bd-8e04f59e9254)
![228720824 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/2a536f25-da70-4cdd-a9b3-9d40b4612f27)
![228720824 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/deb80ec0-bd09-45e9-9b73-417da0cc5665)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Very tenuous, but looks OK?

**Comment by George-Hookway** [comment]
dnu is mostly in agreement with Keystone, though of course this could be wrong.

Epsilon is a little higher than I would have expected, though not absurd.

**Comment by George-Hookway** [comment]
> I'm not absolutely convinced it has dnu correct here. What should we do about these sorts of cases?

I guess if we're not confident with the result, then they shouldn't be reported....

**Comment by nielsenmb** [comment]
I'd buy it if someone told me there are two ridges, I couldn't distinguish them by eye, but if epsilon look right...

**Comment by George-Hookway** [comment]
Baddie star
