### ISSUE TITLE
EPIC 229110376 (Rose)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#117]
![229110376 - 8 - RGB - Echelle](https://github.com/user-attachments/assets/12660cfb-4b03-42d7-9826-5d5095dc4fd5)
![229110376 - 8 - RGB - Mode ID](https://github.com/user-attachments/assets/77d75d93-9514-4914-bdc6-187b1d3f9f7e)
![229110376 - 8 - RGB - Peakbagged Echelle](https://github.com/user-attachments/assets/33718553-4895-413c-a46b-d88dd95c902f)
![229110376 - 8 - RGB - Peakbagging](https://github.com/user-attachments/assets/b2303777-0a05-4d36-8679-801072e45cac)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
I ran this with both giant models, and RGB seemed to work better. I think this is about right, though I'm not so sure about the l=1 modes....

**Comment by nielsenmb** [comment]
For a second I was thinking depressed dipoles, but that wouldn't make sense at this numax.

**Comment by George-Hookway** [comment]
![350_423_f2](https://github.com/user-attachments/assets/5ec17cd6-f70e-435b-ae66-e104f80287c2)

This plot is from Fuller et al. (2015) and shows KIC 8561221 which is known to have depressed modes and at a similar numax. I guess it's just not observed as much at these levels of numax.

**Comment by nielsenmb** [comment]
Hmm I guess, it's just in Denni's paper the density of stars falls off very rapidly with numax, well before the LC nyquist limit. So it just seems suspicious that we happen to see one, and especially in a low resolution spectrum to boot.

![image](https://github.com/user-attachments/assets/359ab18d-5360-4aaa-b13a-191445b51096)

**Comment by nielsenmb** [comment]
That's KIC8561221. Does look sorta similar...

![image](https://github.com/user-attachments/assets/4c0e4e26-37d6-4f30-8684-b4d7a68a0a04)
