### ISSUE TITLE
EPIC 248760285 (James P. Sullivan)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#118]
![248760285 - 8 - SG - Echelle](https://github.com/user-attachments/assets/8cccb357-35e1-4de3-ba94-92888af921f0)
![248760285 - 8 - SG - Mode ID](https://github.com/user-attachments/assets/3e866cfc-7064-4cfe-88ea-5c7b370cba33)
![248760285 - 8 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/0484c54e-1e1b-4e51-ac55-07fe8aeeaa36)
![248760285 - 8 - SG - Peakbagging](https://github.com/user-attachments/assets/95fc0b47-03d0-4235-91a5-5a3349d9aac7)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
![248760285 - 8 - RGB - Echelle](https://github.com/user-attachments/assets/12ca932d-19b2-4aed-82ee-295ad98a6385)

**Comment by George-Hookway** [comment]
The first plot was from the SG model. This second one is RGB

**Comment by grd349** [comment]
Looks ok to me.

**Comment by George-Hookway** [comment]
Accepted as a red giant
