### ISSUE TITLE
EPIC 248849444 (Fours)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#119]
![248849444 - 10 - SG - Echelle](https://github.com/user-attachments/assets/19aa893c-b74f-404d-8c3d-09d21d22d2be)
![248849444 - 10 - SG - Mode ID](https://github.com/user-attachments/assets/e9364196-d0e0-4c4a-8b8a-42f61e69e656)
![248849444 - 10 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/5ab6f315-526a-4220-8aea-ae29bde74aa8)
![248849444 - 10 - SG - Peakbagging](https://github.com/user-attachments/assets/fae6677e-1935-40db-ac8b-4466e4bf839d)

@nielsenmb @grd349

**Comment by grd349** [comment]
Yes - I think so!
