### ISSUE TITLE
EPIC 212708252 (Tom)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#12]
![212708252 - 14 - MS - Echelle](https://github.com/user-attachments/assets/9857c5f2-0182-4e42-8b04-caa52be8f0e9)
![212708252 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/37fcc610-06a5-433e-a931-9b409ec21f10)
![212708252 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/7be71926-ecb1-4c3f-a0c1-2c934f3d8f9e)
![212708252 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/b25523fd-05f8-42c9-9fdb-5074212dec11)

@nielsenmb @grd349

**Comment by grd349** [comment]
Best one yet!
