### ISSUE TITLE
EPIC 211403248 (Patty)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#121]
![211403248 - 6 - RGB - Echelle](https://github.com/user-attachments/assets/f80ac0f2-e770-4efc-a560-68ba660ad594)
![211403248 - 6 - RGB - Mode ID](https://github.com/user-attachments/assets/f1125f95-f58e-4662-a57e-6bd7bafd8c69)
![211403248 - 6 - RGB - Peakbagged Echelle](https://github.com/user-attachments/assets/0c447009-0ba7-4c75-ae5f-e3e5fffb64c3)
![211403248 - 6 - RGB - Peakbagging](https://github.com/user-attachments/assets/53fe7b2b-cc0d-4a81-ad0d-4c30459337db)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Another red giant that I'm not sure whether is working well or not

**Comment by grd349** [comment]
I think pass on this one.

**Comment by nielsenmb** [comment]
The l=2,0 is maybe OK? Definitely not the l=1 though. 

The tall peak isn't a systematic by any chance is it? Looks mighty suspicious that it's so high compared to everything else.

**Comment by George-Hookway** [comment]
It could just be a random spike of noise, but it's not one of the common culprits.

**Comment by George-Hookway** [comment]
May she rest in peace :(
