### ISSUE TITLE
EPIC 246305350 (Nemo)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#122]
![246305350 - 10 - SG - Echelle](https://github.com/user-attachments/assets/e23b379b-266a-41eb-9697-566be3ecdb24)
![246305350 - 10 - SG - Mode ID](https://github.com/user-attachments/assets/c7d7d0f2-6729-406f-9bfd-77d91d3dcc0d)
![246305350 - 10 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/7af10269-0276-4c0d-822e-37e8fac2bac2)
![246305350 - 10 - SG - Peakbagging](https://github.com/user-attachments/assets/fc517698-2fef-4148-8eb0-7a2488c89301)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
I think that looks about right to me?

**Comment by grd349** [comment]
Yeah - I like that!
