### ISSUE TITLE
EPIC 248530476 (The Beatles)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#124]
![248530476 - 8 - MS - Echelle](https://github.com/user-attachments/assets/1af742d6-59b9-492c-b8f5-c885f5d272d1)
![248530476 - 8 - MS - Mode ID](https://github.com/user-attachments/assets/77545ea5-6418-4a3d-99de-3e59089ba0f2)
![248530476 - 8 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/d5aa0e8b-9033-4b10-bf6a-28e7f404896a)
![248530476 - 8 - MS - Peakbagging](https://github.com/user-attachments/assets/c4bfbe7f-1b4f-4dd9-a34d-b7849a907c16)

@nielsenmb @grd349

**Comment by grd349** [comment]
I guess if epsilon is correct...

**Comment by George-Hookway** [comment]
@nielsenmb, does it need more work, or should I let it be?

**Comment by nielsenmb** [comment]
I think let it be!
