### ISSUE TITLE
EPIC 248777106 (The Great Goblin)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#125]
![248777106 - 8 - MS - Echelle](https://github.com/user-attachments/assets/569c39fb-72f0-409c-96c1-da098966430d)
![248777106 - 8 - MS - Mode ID](https://github.com/user-attachments/assets/c094b48e-9d2c-4ad1-aacb-f36b981ece72)
![248777106 - 8 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/14d2d89d-0250-4bc8-8f42-9143939e0bfc)
![248777106 - 8 - MS - Peakbagging](https://github.com/user-attachments/assets/14691d04-cc25-452f-b20a-06d03b697383)

@nielsenmb @grd349

**Comment by grd349** [comment]
Yes yes and yes
