### ISSUE TITLE
EPIC 248891803 (Henry Van Statten)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#126]
![248891803 - 8 - MS - Echelle](https://github.com/user-attachments/assets/76758c3e-19ca-47c1-bc61-5bfac07fbc41)
![248891803 - 8 - MS - Mode ID](https://github.com/user-attachments/assets/742858df-6ed7-4536-a692-f5bae17d298e)
![248891803 - 8 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/ec41895c-cc00-4636-9c93-a30359414260)
![248891803 - 8 - MS - Peakbagging](https://github.com/user-attachments/assets/be994370-bb60-447b-b563-c27389adc20c)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Epsilon was an initial cause for pause as it seemed a little too low, but I think it's found the correct solution.

**Comment by grd349** [comment]
Looks ok to me.
