### ISSUE TITLE
EPIC 249602800 (Jar Jar Binks)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#127]
![249602800 - 12 - MS - Echelle](https://github.com/user-attachments/assets/183a7025-3edc-4485-8fe2-2d69cc4d255d)
![249602800 - 12 - MS - Mode ID](https://github.com/user-attachments/assets/442cfcc0-2ceb-473a-8a99-eabd7f6972d9)
![249602800 - 12 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/33678278-3183-4420-ae23-9e1b6d422888)
![249602800 - 12 - MS - Peakbagging](https://github.com/user-attachments/assets/c4375fae-0248-4178-8013-77e8899bc165)

@nielsenmb @grd349

**Comment by grd349** [comment]
Yes!
