### ISSUE TITLE
EPIC 246257644 (Mike Wazowski)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#128]
![246257644 - 14 - MS - Echelle](https://github.com/user-attachments/assets/10ea7e17-ed0f-4fad-95e2-0de1603a447f)
![246257644 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/1e6336bd-3002-4b5e-b1d6-877158a5ab28)
![246257644 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/9d66144a-4bd8-4542-959b-dcfe65321ea5)
![246257644 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/a5b55682-639d-4df8-b895-bebcf3030c70)

@nielsenmb @grd349

**Comment by grd349** [comment]
Looks good to me!
