### ISSUE TITLE
EPIC 236224056 (Father Christmas)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#129]
![236224056 - 10 - SG - Echelle](https://github.com/user-attachments/assets/55770fd3-07bf-4ef4-a359-a36c58abf7fa)
![236224056 - 10 - SG - Mode ID](https://github.com/user-attachments/assets/3c54f9c2-a6e1-41f2-a302-f83cfcb1ef0d)
![236224056 - 10 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/f80c6c76-63bc-4b4e-9e52-0b84f05507f1)
![236224056 - 10 - SG - Peakbagging](https://github.com/user-attachments/assets/aee50b9a-bd67-4641-8205-d0737ee8fb96)

@nielsenmb @grd349

**Comment by grd349** [comment]
This might be my favourite SG yet! (perhaps RG but whatever)

**Comment by nielsenmb** [comment]
I do! Looks good.
