### ISSUE TITLE
EPIC 214073502 (Peter)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#13]
![214073502 - 14 - MS - Echelle](https://github.com/user-attachments/assets/8a0e66e2-f4bd-4118-8b4a-84c78584dce2)
![214073502 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/592101b0-8dcc-4f98-9629-652295a3840f)
![214073502 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/325b6e15-aed1-480e-82b1-f1fd1f1d66fa)
![214073502 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/6b989b9e-5909-480f-9fdb-455846ec0c95)

@nielsenmb @grd349

**Comment by grd349** [comment]
Glorious!

**Comment by nielsenmb** [comment]
The curvature in the mode ID seems a bit off. 

Notice the l=0 modes on the low side of numax are floating around where there is no power. 

This seems to have propagated to the peakbagging too? It's hard to see with this level of zoom.

**Comment by George-Hookway** [comment]
![214073502 - 14 - MS - Echelle](https://github.com/user-attachments/assets/261d4983-0bb8-418f-b1de-e4f4887c1146)
![214073502 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/a77063de-f576-45d2-95dc-2515c1d40036)
![214073502 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/a0109fbb-2ee5-436c-9ee8-e0c4066bf325)
![214073502 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/348c4bdb-6f33-4547-96a4-fea1f7b06352)

**Comment by George-Hookway** [comment]
It still has what seems to be floating modes in the Mode ID spectrum, though it looks fine in the final peakbag

**Comment by nielsenmb** [comment]
Looking at this a bit more closely, I think it's just due to the realization of the spectrum. You can see this a bit more clearly now in the echelle, there are two orders at around 2500muHz  where there is just no power from the l=0, which makes it look like the solution as some floating modes, when in fact it's correct. 

I'm now very confident this is correct.
