### ISSUE TITLE
EPIC 249939354 (Chicken)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#142]
![249939354 - 6 - RGB - Echelle](https://github.com/user-attachments/assets/4335c166-7591-4045-88cb-eec38b05baa2)
![249939354 - 6 - RGB - Mode ID](https://github.com/user-attachments/assets/b06dee43-8180-481c-87ed-23946297a30c)
![249939354 - 6 - RGB - Peakbagged Echelle](https://github.com/user-attachments/assets/c2b568ee-6027-42e7-9e28-461596be3b60)
![249939354 - 6 - RGB - Peakbagging](https://github.com/user-attachments/assets/0f79dea6-85a0-4484-9c21-d8ce166b373f)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
I'm not certain about this one, but it might be right

**Comment by grd349** [comment]
I am certain it could be wright. I am uncertain it is right.  This is clearly a red giant and the data is not great. I propose dropping from sample.

**Comment by nielsenmb** [comment]
I don't think this is correct. There are too many missed modes. 

Was this with manually defining the DPi1 prior?

I worry that the resolution is too low for evolved stars, so most peaks are defined by maybe just 1-2 frequency bins. So the prior can easily dominate in this case. It's an effect I've seen a lot in TESS, where we usually only have 1 month of data.

**Comment by George-Hookway** [comment]
To the abattoir you go
