### ISSUE TITLE
EPIC 246099088 (Sylvester)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#15]
![246099088 - 14 - MS - Echelle](https://github.com/user-attachments/assets/d3691b55-5c67-40e4-bd5f-4b002b6a8abf)
![246099088 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/b7cdbe41-a833-4b7f-a8bc-e7379f4fabee)
![246099088 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/e1d98cb1-446b-44d3-bee3-0b5bc3141bae)
![246099088 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/2b40384e-f2ab-40b0-8bc2-bf79cbfd04e7)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
I've seen prettier echelle diagrams, but it seems to end up okay. And epsilon is good as well.

**Comment by nielsenmb** [comment]
This one needs verification with smaller symbols in the echelle.

**Comment by George-Hookway** [comment]
When I ran improved plots for it, the dnu issue became clear with this one :/

**Comment by nielsenmb** [comment]
Time to make some reference plots!

**Comment by George-Hookway** [comment]
![246099088 - 8 - MS - Echelle](https://github.com/user-attachments/assets/a9864ba6-c7e3-4db9-b3ff-189cab4ffcce)
![246099088 - 8 - MS - Mode ID](https://github.com/user-attachments/assets/baf70941-1e6e-437c-b690-629fc3a80fb2)
![246099088 - 8 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/f22d694c-8a45-4054-b7e3-5d241678a130)
![246099088 - 8 - MS - Peakbagging](https://github.com/user-attachments/assets/21488db0-8f77-47c6-b499-80296e95a7ce)
