### ISSUE TITLE
EPIC 246260292 (David)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#18]
![246260292 - 14 - MS - Echelle](https://github.com/user-attachments/assets/c8a6b29a-072c-455f-8d80-a466a54105d6)
![246260292 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/72437d25-0ce5-4712-a622-e7c38c7d5446)
![246260292 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/2cabf1e7-5e9c-4aac-baf4-6914c4cdde35)
![246260292 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/d3666672-4160-47a4-8400-3d63ef2397b6)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Yup

**Comment by George-Hookway** [comment]
![246260292 - 14 - MS - Echelle](https://github.com/user-attachments/assets/6d8563b6-2c81-45fa-9ec1-733d060f248b)
![246260292 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/d22fb9b3-bdd3-4bf9-bcdc-36c0154a12bd)
![246260292 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/fb6488ef-f50c-46bc-b256-59753910e088)
![246260292 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/f9ace5d4-003b-49fa-a23f-4e4a44511293)

**Comment by George-Hookway** [comment]
With this one, I reduced Teff from 6590 --> 6471, which increased epsilon by 0.3

**Comment by George-Hookway** [comment]
@grd349, like this star do you?

**Comment by grd349** [comment]
There is no like, only love
