### ISSUE TITLE
EPIC 246301897 (Matt)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#19]
![246301897 - 14 - MS - Echelle](https://github.com/user-attachments/assets/0e165919-439e-4526-afae-ed8966a6eeb6)
![246301897 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/83c3cb54-56be-4e07-b006-84a7475b711a)
![246301897 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/dbd191eb-a86d-4166-9314-da0b58b83ea0)
![246301897 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/23d7278b-61c5-442c-8ee2-14fe59063e6f)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Yup

**Comment by George-Hookway** [comment]
![246301897 - 14 - MS - Echelle](https://github.com/user-attachments/assets/113287f6-8d05-4508-8ff3-ace652f8ee9f)
![246301897 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/9c10b6de-19c0-4ff3-9a2f-d296b225d2a6)
![246301897 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/6299851c-62a9-4d3e-aeee-a0b4f7df9c17)
![246301897 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/6812f0a8-9e41-4c82-9f6b-b662e7b6ad39)

**Comment by nielsenmb** [comment]
Looks good!

**Comment by grd349** [comment]
OK - yes, I think so.
