### ISSUE TITLE
EPIC 241011563 (Thunder Star)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#2]
![241011563 - 11 - MS - Echelle](https://github.com/user-attachments/assets/3d33f558-51bd-4512-b6d7-64332400489e)
![241011563 - 11 - MS - Mode ID](https://github.com/user-attachments/assets/9eb29e38-0d5f-492d-bca5-9b7f926827ea)
![241011563 - 11 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/ed5f627d-7644-4cfc-af39-1b949851b1df)
![241011563 - 11 - MS - Peakbagging](https://github.com/user-attachments/assets/6ffed3e3-efaf-4ea6-932f-b5d8de10b972)

@nielsenmb @grd349

**Comment by grd349** [comment]
Do we think we might have missed low-frequency modes here?

**Comment by nielsenmb** [comment]
Possibly and l=1 mode, but with so many radial orders will that change anything?

**Comment by grd349** [comment]
Low-frequency modes are super important because they help anchor the surface correction. 

But in general, we want to report as many modes as sensible.

**Comment by George-Hookway** [comment]
I expanded the range to include an extra mode up and down.

![241011563 - 13 - MS - Mode ID](https://github.com/user-attachments/assets/815c2cd0-9337-4dfb-8cc6-012d17064e2b)
![241011563 - 13 - MS - Frequencies](https://github.com/user-attachments/assets/fbd41721-f11e-4339-8fc9-d215b08f2b9f)
![241011563 - 13 - MS - Echelle](https://github.com/user-attachments/assets/2d399da7-eae1-415c-b4b5-cb068242c524)
![241011563 - 13 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/9c0efb6b-b82e-472d-85d9-da07270a8681)
![241011563 - 13 - MS - Peakbagging](https://github.com/user-attachments/assets/3f67462f-84f9-4479-a8aa-a799644c15bb)

**Comment by grd349** [comment]
Awesome - that looks good to me!
