### ISSUE TITLE
EPIC 246758642 (Professor X)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#20]
![246758642 - 14 - MS - Echelle](https://github.com/user-attachments/assets/b4f8f100-6633-4244-97bd-0e7881146ebb)
![246758642 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/1d5db8ca-8b95-441b-bb47-83e9ce679bb9)
![246758642 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/dd747611-f2eb-4eb5-98e6-ab01d201a016)
![246758642 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/4992918f-9cd0-40de-a68e-629861560d48)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks mildly warm this star? Late F?

I think the mode ID solution is bi-modal cause the curvature term isn't strong enough. It's not to say it's wrong, there may be a glitch moving the modes.

**Comment by George-Hookway** [comment]
![246758642 - 16 - MS - Echelle](https://github.com/user-attachments/assets/1a40a3aa-c71f-463b-8d45-72ecd383e82a)
![246758642 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/8b1c8940-c75a-4de7-b075-926dae8a42b2)
![246758642 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/56a09cdc-fe58-4a80-a31e-ba575b09df01)
![246758642 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/a4f84a73-9ee6-4544-9950-30db69ae6a65)

Could the wibbly-wobbly nature of this star be caused by, perhaps, another star.....?

**Comment by nielsenmb** [comment]
I think you would see the effect in both ridges no?

**Comment by George-Hookway** [comment]
Sure, I get you. Just extreme curvature, then?

**Comment by nielsenmb** [comment]
I think you'd see that in the l=2,0 ridge as well, so I'm not sure what's going on here to be honest.
