### ISSUE TITLE
EPIC 247906277 (Jodie)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#21]
![247906277 - 14 - MS - Echelle](https://github.com/user-attachments/assets/1531e982-1250-45e5-85b6-1fd925767aba)
![247906277 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/f308f67c-66a7-430d-ad5c-b7c971745864)
![247906277 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/e9847170-c511-44ff-a438-b3054f605bc7)
![247906277 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/0b4dd895-b23b-4801-91e9-7699289ed66a)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Yup

**Comment by George-Hookway** [comment]
![247906277 - 14 - MS - Echelle](https://github.com/user-attachments/assets/e35c5a57-9b55-44e9-af85-31497659bc63)
![247906277 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/10be10d3-632b-4b35-9643-357f8c3d55b0)
![247906277 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/ab17e837-df49-4b43-a0bf-9cdc6538789e)
![247906277 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/dca2f136-d235-4597-9d5c-e5d204ee8fa0)

**Comment by George-Hookway** [comment]
Updated plots

**Comment by grd349** [comment]
Oh yes.

**Comment by nielsenmb** [comment]
Very nice. Nice high numax too.
