### ISSUE TITLE
EPIC 248593082 (Dr Who)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#24]
![248593082 - 14 - MS - Echelle](https://github.com/user-attachments/assets/06a099d0-77f1-4e18-beae-3bad74e4b885)
![248593082 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/a36bba40-d0a0-4f88-b6c6-15bc9bc4b0f6)
![248593082 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/37075b32-48f9-40da-97d9-aaa9bc54b613)
![248593082 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/f333be91-501f-4fe8-99db-4a3b48f37cb0)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Definitely the best peakbagged spectrum

**Comment by George-Hookway** [comment]
Right, I'll have a look in the plotting file and change it

**Comment by George-Hookway** [comment]
![248593082 - 16 - MS - Echelle](https://github.com/user-attachments/assets/b7328a66-2380-4b8d-8af7-6c2e0ac16fa0)
![248593082 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/2605932c-a22b-4a06-b530-d1ca9e263e79)
![248593082 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/fb94b2db-e8ac-4bc5-bc97-edef16cd2956)
![248593082 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/2843dc64-3aad-4462-83ec-bfef5fc0852c)

**Comment by George-Hookway** [comment]
Got new plots for this star. Epsilon still works with it being ~0.96

**Comment by grd349** [comment]
If epsilon is as expected then I am happy!

**Comment by nielsenmb** [comment]
I'm gonna take a wild stab and say epsilon is as expected based on the mode width and envelope width. The linewidths at low frequency are a bit narrower and it looks like it's getting the right l=1 at least.
