### ISSUE TITLE
EPIC 248842300 (Plo Koon)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#25]
![248842300 - 14 - MS - Echelle](https://github.com/user-attachments/assets/3ebb07f4-73db-460d-944a-139c9e761674)
![248842300 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/b08bb699-0168-4915-99a7-6e1c154f1471)
![248842300 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/3525d27e-dbae-4c70-90eb-9c3d20c9be02)
![248842300 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/65647f9e-109a-4f52-8180-ebb7972629b5)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks good, but hard to say if the mode ID is correct. Does this fit with the expected epsilon?

**Comment by George-Hookway** [comment]
PBjam uses 0.87, and my model suggests 0.99. So it could be believable

**Comment by nielsenmb** [comment]
Yeah it's probably OK then.

**Comment by George-Hookway** [comment]
![248842300 - 8 - MS - Echelle](https://github.com/user-attachments/assets/d1b5ff94-72a7-434e-a608-aea08536e080)
![248842300 - 8 - MS - Mode ID](https://github.com/user-attachments/assets/37e4c212-1311-4308-bb2d-ce62eb00b399)
![248842300 - 8 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/af1eff48-e163-49fa-a015-32b3238353ff)
![248842300 - 8 - MS - Peakbagging](https://github.com/user-attachments/assets/b6ca0919-130d-4945-adb9-3c1ffa11d2b9)

**Comment by grd349** [comment]
Very hard to tell here. Is there a systematic?

**Comment by George-Hookway** [comment]
You're thinking the peak at 1600? I'm not sure....
