### ISSUE TITLE
EPIC 228818122 (Ki-Adi-Mundi)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#28]
![228818122 - 14 - MS - Echelle](https://github.com/user-attachments/assets/fedc970b-fc72-41ab-9d91-b11719f0cab7)
![228818122 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/174cc98e-1e32-435a-b595-1e1db1b2b0eb)
![228818122 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/e71c86dd-5fdb-445d-beac-8c9da878d994)
![228818122 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/ee829106-94c8-440a-b022-bc05a90b31c5)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
It uses an epsilon of 0.916, which seems about right to me

**Comment by grd349** [comment]
What is the Teff of this star?

**Comment by George-Hookway** [comment]
6455K

**Comment by grd349** [comment]
F indeed! How are those updated plots with more smoothing going?  they might help us here.

**Comment by George-Hookway** [comment]
Unfortunately I left "Save=False" so everything that ran on Friday wasn't saved. I'm running it again now

**Comment by George-Hookway** [comment]
![228818122 - 10 - MS - Echelle](https://github.com/user-attachments/assets/6e9cca71-3a8f-4738-a1ae-f09fee613f8d)
![228818122 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/f5e38ce2-3d9e-4be1-b478-6204bf42e2ca)
![228818122 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/113f7f8a-67d7-4d89-9dd9-bb951c166808)
![228818122 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/a08598d7-8d87-45a5-a3b4-1eac9ff48400)

**Comment by George-Hookway** [comment]
Another case of the dip in the spectrum. dnu and epsilon line up pretty nicely, though very few of these modes will be worth reporting
