### ISSUE TITLE
EPIC 246069493 (Pants)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#3]
![246069493 - 8 - MS - Echelle](https://github.com/user-attachments/assets/622b2065-13f2-4514-a626-cfdfda3c5161)
![246069493 - 8 - MS - Mode ID](https://github.com/user-attachments/assets/deeb6b4d-7f8a-4ece-b251-1ced5ddca73a)
![246069493 - 8 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/615ff428-e908-4687-a49c-be39e9a2ee00)
![246069493 - 8 - MS - Peakbagging](https://github.com/user-attachments/assets/4533b04a-c0cc-49c6-bb09-d52017f9b3c4)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks good to me!

**Comment by grd349** [comment]
Possible extra modes at high-frequency?

**Comment by George-Hookway** [comment]
I've added an extra mode at higher frequency

![246069493 - 9 - MS - Mode ID](https://github.com/user-attachments/assets/81202782-6d76-41fc-9c3e-9e74c23d4810)
![246069493 - 9 - MS - Frequency Range](https://github.com/user-attachments/assets/26fbdc9e-0d03-49f6-93b3-28cbc853cc03)
![246069493 - 9 - MS - Echelle](https://github.com/user-attachments/assets/bfbe114b-4576-4346-a7a8-e27f4fb00194)
![246069493 - 9 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c69ce910-73f6-432d-b432-4730423c233f)
![246069493 - 9 - MS - Peakbagging](https://github.com/user-attachments/assets/5560672d-1dff-4869-b975-a03cdf91adb1)

**Comment by grd349** [comment]
Looks good to me!
