### ISSUE TITLE
EPIC 203530127 (Oppo Rancisis)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#31]
![203530127 - 14 - MS - Echelle](https://github.com/user-attachments/assets/b84910bc-87e2-433e-a093-22d72a7a4a31)
![203530127 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/cceabcd1-1278-428a-8735-05193d207b6d)
![203530127 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/3a894ba3-3f12-489b-9d30-6a67864ff99e)
![203530127 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/63c176f6-c512-4736-b609-96dc8ab31082)

@nielsenmb @grd349

**Comment by grd349** [comment]
Lovely!

**Comment by nielsenmb** [comment]
Yup!
