### ISSUE TITLE
EPIC 211780967 (Even Piell)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#32]
![211780967 - 14 - MS - Echelle](https://github.com/user-attachments/assets/72b0e3f2-6b4e-4638-be8c-5698cf2ca16c)
![211780967 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/48d764cf-8d14-4423-880a-44a5689fd5db)
![211780967 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c63fd96f-4448-4e37-b3de-8fc3e60261af)
![211780967 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/19aee84e-7e64-44b6-b19e-9e4457700f9f)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
The Mode ID seems to miss by a couple microHz, but the final spectrum fits really nicely.

**Comment by grd349** [comment]
Is this star hot?  I worry about the mode ID here.

**Comment by George-Hookway** [comment]
6432K

**Comment by grd349** [comment]
Could you check the epsilon here? Ta

**Comment by George-Hookway** [comment]
PBjam uses 0.944

**Comment by nielsenmb** [comment]
I think that tracks? It's not super F-typey judging by the linewidths.

**Comment by George-Hookway** [comment]
![211780967 - 14 - MS - Echelle](https://github.com/user-attachments/assets/5b18a480-f12e-4976-b30b-1cf5992cfd9a)
![211780967 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/e66e4755-4fa0-4f1a-ac2c-1bc7ed4a812c)
![211780967 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/0992539a-b33f-4991-8a78-f3008123de20)
![211780967 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/f43be590-63ce-41a4-a9cb-fdde78adc8d0)

**Comment by George-Hookway** [comment]
Actually, I might see if it can get even higher frequency modes

**Comment by George-Hookway** [comment]
![211780967 - 20 - MS - Echelle](https://github.com/user-attachments/assets/94021f22-092b-493b-8a0a-cb11b8e2e75c)
![211780967 - 20 - MS - Mode ID](https://github.com/user-attachments/assets/f79a338b-213b-4dfd-bebd-41e4d0f7332c)
![211780967 - 20 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/5f884195-e0bc-4b24-893c-a4b333509186)
![211780967 - 20 - MS - Peakbagging](https://github.com/user-attachments/assets/cde90381-e8db-4ab3-93d6-642cdbc1d40b)

**Comment by George-Hookway** [comment]
I don't think there was any real benefit gained from adding more modes, but here it is anyway.

**Comment by nielsenmb** [comment]
Yeah, you're probably right. Think this one can be ticked off.

**Comment by grd349** [comment]
Agreed - tick it off! :)
