### ISSUE TITLE
EPIC 212026577 (Adi Gallia)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#33]
![212026577 - 14 - MS - Echelle](https://github.com/user-attachments/assets/9123489a-efd7-4576-9ba2-9bc25d7f452b)
![212026577 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/84935814-e098-4884-a020-b981206f64b2)
![212026577 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/2ddbcbff-e949-447f-a782-f0df26983106)
![212026577 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/2b343c8b-bcd6-4f14-8ea9-9cc58398fbc3)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Nice!

**Comment by grd349** [comment]
Amazing
