### ISSUE TITLE
EPIC 212709512 (Depa Billaba)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#36]
![212709512 - 14 - MS - Echelle](https://github.com/user-attachments/assets/fee92918-7e0b-4145-bf75-f1be04131a71)
![212709512 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/ca6cf02e-9597-4024-81d8-98dd35725660)
![212709512 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/03738363-d8ff-45a4-8423-556e833caded)
![212709512 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/ad8469f3-e269-481a-ae1e-b612b29c3d8f)

@nielsenmb @grd349

**Comment by grd349** [comment]
Oh yes!

**Comment by nielsenmb** [comment]
yup
