### ISSUE TITLE
EPIC 212710665 (Shaak Ti)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#37]
![212710665 - 14 - MS - Echelle](https://github.com/user-attachments/assets/a3b42039-ea59-420d-b265-b88990c92a4b)
![212710665 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/0e325105-738b-4c73-9738-f5741244cc08)
![212710665 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/74271928-da72-46c8-8b73-87fecf1ca097)
![212710665 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/736eda7a-fec1-4b4c-aab9-e203a8f3d9ba)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Very nice.

**Comment by grd349** [comment]
Wowser
