### ISSUE TITLE
EPIC 213841509 (Kit Fisto)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#39]
![213841509 - 14 - MS - Echelle](https://github.com/user-attachments/assets/c66018e3-d975-430f-82b8-7546947d98ab)
![213841509 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/64e5f4dc-00ec-4d6d-bf6f-e8b9a645f567)
![213841509 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/f24d2d34-7be7-4ac5-bf52-36a2fb297277)
![213841509 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/fe287525-f3fd-46a4-b6b1-13e22c1f0482)

@nielsenmb @grd349

**Comment by grd349** [comment]
I wish they were all like this.

**Comment by nielsenmb** [comment]
Good
