### ISSUE TITLE
EPIC 246438837 (Socks)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#4]
![246438837 - 11 - MS - Echelle](https://github.com/user-attachments/assets/f9f4aaaa-64e0-47ef-8224-6d876cb3a3fc)
![246438837 - 11 - MS - Mode ID](https://github.com/user-attachments/assets/614fa28b-c85c-4ab6-8224-b968ca93ef35)
![246438837 - 11 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/5e0ab58f-fd7f-483c-9356-3f13a7e90f40)
![246438837 - 11 - MS - Peakbagging](https://github.com/user-attachments/assets/96d704ca-412d-4dc9-893e-b976f7e65285)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
There's a lot of residual systematics at low frequency for this one by the looks of it. 

Otherwise it looks good to me!

**Comment by grd349** [comment]
Yeah - I think I am happy.
