### ISSUE TITLE
EPIC 216228024 (Obi-Wan Kenobi)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#40]
![216228024 - 14 - MS - Echelle](https://github.com/user-attachments/assets/8b5acc20-d3c2-4de4-a04e-2628732c0af7)
![216228024 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/ba9679ae-4641-46c9-9418-c477a874cb52)
![216228024 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/ad92b981-88bd-48be-8411-edd2f06a7db7)
![216228024 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/15968926-b213-4c05-9b05-c71005702dff)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Again, probably an excessive amount of modes at low frequency. The curvature is not strong with this one though, so might be OK.

**Comment by grd349** [comment]
I'm happy with this!
