### ISSUE TITLE
EPIC 220374993 (Coleman Kcaj)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#41]
![220374993 - 14 - MS - Echelle](https://github.com/user-attachments/assets/0c319e68-8bc3-413f-8817-71531a8427fa)
![220374993 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/6fe3579c-6fe2-44bb-b1ce-0b0a7848a911)
![220374993 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/75f7b73e-5bcf-4353-ad3e-a1401ad2f34e)
![220374993 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/dfcc3670-49a3-4a69-8aa1-4c5661daae07)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
yup

**Comment by grd349** [comment]
Agreed.
