### ISSUE TITLE
EPIC 220623859 (Stass Allie)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#42]
![220623859 - 14 - MS - Echelle](https://github.com/user-attachments/assets/ac1d625c-e3af-4f34-a303-6934ab3f4433)
![220623859 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/d2277d2f-36da-41e0-b7db-49c87989d198)
![220623859 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/01faec95-d1a0-43c4-9a94-c20e51241c4d)
![220623859 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/ff9846dc-d1c4-42d5-a750-9e237bacee60)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Nice

**Comment by grd349** [comment]
Amazing.
