### ISSUE TITLE
EPIC 224535896 (Agen Kolar)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#43]
![224535896 - 14 - MS - Echelle](https://github.com/user-attachments/assets/8e467166-2807-4578-9c21-e9fb8279aeea)
![224535896 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/4bbc0e94-3063-497d-92ba-2864ce328303)
![224535896 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c56ef9b2-7b80-4563-bf3f-1f9e2ee403d6)
![224535896 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/03faf2a0-18d6-400c-8cdf-3a878f7ff20c)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Yup

**Comment by grd349** [comment]
Dreamy!
