### ISSUE TITLE
EPIC 228984381 (Anakin Skywalker)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#44]
![228984381 - 14 - MS - Echelle](https://github.com/user-attachments/assets/acfbad9c-a2ca-4b6b-bc99-8ea43ebd2e8d)
![228984381 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/d3cbe660-68ce-4c89-b227-b933078bbb1b)
![228984381 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c64e08a6-e4b6-412f-b143-76a89991fb6a)
![228984381 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/05bbf87d-c72c-480d-84bb-953f19b4260a)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Could this be on the sub-giant boundary?

**Comment by nielsenmb** [comment]
Yeah if it isn't it's very close. There's a smudge of power at ~(50, 1000) which could be an avoided crossing creeping up in frequency. The SNR isn't high enough there to tell though. 

It looks good though.

**Comment by grd349** [comment]
OMG - yes, that'll do.
