### ISSUE TITLE
EPIC 230748783 (The Nameless)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#45]
![230748783 - 14 - MS - Echelle](https://github.com/user-attachments/assets/d3dba4b1-1583-4c15-8c7e-6965c73ebbb3)
![230748783 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/d861b6a7-74c8-4d75-8280-26956fa8ddc9)
![230748783 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/a297b095-7e80-4af3-a2af-fda1e923951a)
![230748783 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/82f0f7c7-437e-40cb-9ba7-425a05712429)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Huh, never seen something like this before. Probably just the realization noise, but the distribution of power looks funky. 

With this few clear modes just double check epsilon. Looks fine though.

**Comment by George-Hookway** [comment]
Epsilon of 1.50

**Comment by grd349** [comment]
Ummmmm?

**Comment by George-Hookway** [comment]
What about this one is funky?

**Comment by grd349** [comment]
It's not based on much and the l=1 is hard to see.  I'm sure it's fine.

**Comment by nielsenmb** [comment]
Just a curiosity really, but to me it's just that the envelope is very asymmetric. 

There's usually some random asymmetric due to the realization of the spectrum, but this seems pretty strong.
