### ISSUE TITLE
EPIC 231478973 (Thorin Oakenshield)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#46]
![231478973 - 14 - MS - Echelle](https://github.com/user-attachments/assets/d51ec68f-5c60-4a8c-9db2-038dc57dfac1)
![231478973 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/c1f9ce62-1805-4043-a77e-6ce4b6c74f03)
![231478973 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/2624eba3-9d0e-4930-b37b-88f30e913d60)
![231478973 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/0914d740-2ed3-4e6f-b879-9276e32c8c3d)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Yup

**Comment by grd349** [comment]
I will not parley, as I have said, with armed men at my gate. Nor at all with the people of the Elvenking, whom I remember with small kindness. In this debate they have no place. Begone now ere our arrows fly!  Yes

**Comment by George-Hookway** [comment]
https://github.com/user-attachments/assets/70e4052d-034e-4627-a2ee-cd9375d4b66b
