### ISSUE TITLE
EPIC 235124375 (Kili)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#48]
![235124375 - 14 - MS - Echelle](https://github.com/user-attachments/assets/93dbc244-497f-4ea0-9ce4-20484ba93892)
![235124375 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/ad08699a-f7cc-4244-b1de-95779d4b36ff)
![235124375 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/9b738127-8325-4c5b-8c26-f822b448b3c2)
![235124375 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/56edc0e7-2c4d-4ac0-b265-38d1d44e6c54)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
yup

**Comment by grd349** [comment]
Indeed.
