### ISSUE TITLE
EPIC 242184803 (Balin)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#49]
![242184803 - 14 - MS - Echelle](https://github.com/user-attachments/assets/ef178ed6-7e99-4919-8e8f-404d0e26f948)
![242184803 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/9ea2bb90-10b8-4271-8d20-045f0d1170db)
![242184803 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c42eb83a-1ee8-4d27-aa77-636fb8df9e0e)
![242184803 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/837d39af-3261-4aa4-afa2-406fd085a9c4)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Thumbs up.

**Comment by grd349** [comment]
Yeah - I guess I am happy. I guess this is just a low snr example.
