### ISSUE TITLE
EPIC 236012973 (Muffin the Mule)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#5]
![236012973 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/4df0d6c8-e39e-4a0b-9a03-4e93fe99821f)
![236012973 - 10 - MS - Frequency Range](https://github.com/user-attachments/assets/b3212c00-93c9-4d44-af01-69a45e3ddb23)
![236012973 - 10 - MS - Echelle](https://github.com/user-attachments/assets/52239a2d-b7bf-42f7-af10-09745afdcf7a)
![236012973 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/ea6e5197-0419-4180-b356-1c2e2bfe4384)
![236012973 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/20f94ebd-b99b-44e0-b922-d9d1c324f575)

@nielsenmb @grd349

**Comment by grd349** [comment]
Ok - looks good but I worry about the highest frequency l=0 mode.  We should discuss on Friday.

**Comment by nielsenmb** [comment]
Sorry I didn't get the notification about this issue.

Fit looks great, but the initial numax is just too low by 1-2 dnu, so the model can't see the high frequency bits, and only sees noise at the low end. Seems like the Keystone is off one again.

**Comment by George-Hookway** [comment]
I can see numax being half a dnu too low.

At what point should I be confident enough to alter the inputted numax?

**Comment by nielsenmb** [comment]
I would say when the numax you get out is >1 dnu different or so, you might also be able to judge it by eye. The envelope should be roughly symmetric around numax, so if the keystone numax is clearly off-center then it might be worth tweaking it. 

Ultimately it doesn't make much of a difference to the frequencies you get out, it's just whether you catch the low/high modes.

**Comment by George-Hookway** [comment]
![236012973 - 14 - MS - Echelle](https://github.com/user-attachments/assets/b3859dd2-a779-4c8d-90fb-17a4e66e8584)
![236012973 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/49392174-5219-44b9-a9f2-9217fbb028b8)
![236012973 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/3e074f1e-9ce8-480b-b5bb-5f077aa38863)
![236012973 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/affa0172-0e2f-4d3b-8837-eb37f957516a)

**Comment by George-Hookway** [comment]
This one ran again, but with higher Np.

Keystone suggests numax ~ 2550, and it does look like the spectrum peaks in power at about that level, but PBjam seems to have favoured adding modes of lower frequency, thus lowering the centre of the peakbagged spectrum.

**Comment by nielsenmb** [comment]
I think this might just be an issue with adding radial orders iteratively top and bottom. Hard to get around.

The result looks good to me though.

**Comment by George-Hookway** [comment]
I think then that this one is considered completed.
