### ISSUE TITLE
EPIC 245972483 (Dwalin)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#50]
![245972483 - 14 - MS - Echelle](https://github.com/user-attachments/assets/2c58bfe4-f357-41cd-b66b-e46716fd88d4)
![245972483 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/45cd7308-07a5-4d52-aff2-e591ef5feb8a)
![245972483 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/e1febe86-92d0-4718-b925-5ae85b102579)
![245972483 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/ce05e9cc-7ea1-4e3d-8a59-3fb49b7d87b0)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
slam dunk
