### ISSUE TITLE
EPIC 246011640 (Oin)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#51]
![246011640 - 14 - MS - Echelle](https://github.com/user-attachments/assets/854a734f-106c-41c0-b523-3bdcba31abd5)
![246011640 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/d7bc9e00-1430-46d6-8cc7-049c8536e5d6)
![246011640 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/0f72a2a2-1cc1-4498-90c7-8e9d2394197d)
![246011640 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/60e8ecb9-9786-4bb4-83a7-661be5a88618)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
This one is very close to being a sub-giant, but it looks like it's a bit higher Teff which is probably why we aren't seeing an avoided crossing yet.

**Comment by grd349** [comment]
Love it!
