### ISSUE TITLE
EPIC 246025837 (Gloin)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#52]
![246025837 - 14 - MS - Echelle](https://github.com/user-attachments/assets/ac2ea7a4-9286-4814-9252-c65918a6fe7e)
![246025837 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/2cdd41a9-005e-4dae-9e56-c476dce85b48)
![246025837 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/ac9244b3-9102-44e1-a994-24d927cf953c)
![246025837 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/8b240ce5-e7a8-4be3-a6e4-e92e489a9bdb)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks good. The l=2 mode at ~(30, 1600) is a bit weird, but it's what the spectrum says so...

**Comment by grd349** [comment]
Glorious! l=2 bumped mode?

**Comment by nielsenmb** [comment]
I guess that's for the modelers to decide. Either way we've measured it.
