### ISSUE TITLE
EPIC 246358796 (Dori)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#53]
![246358796 - 14 - MS - Echelle](https://github.com/user-attachments/assets/58be80f0-d292-41f8-a8a2-cf18bbf60856)
![246358796 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/83ea0670-d0f3-423d-b23f-9c45fb7e4d5c)
![246358796 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/680b0e7b-0961-4537-bffc-11ad508cf0b6)
![246358796 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/7fb367d1-c033-479e-bb5d-1354d9a489a1)

@nielsenmb @grd349

**Comment by grd349** [comment]
Oh - we are discussing this!  :)

**Comment by George-Hookway** [comment]
If this one is a binary, should the higher frequency modes have tight priors applied to them to prevent the companion being picked up?
