### ISSUE TITLE
EPIC 246843060 (Nori)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#54]
![246843060 - 14 - MS - Echelle](https://github.com/user-attachments/assets/3d2fcc8b-2ebd-46b1-8cc9-f8186a7ce82a)
![246843060 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/82a7ae3e-e759-4c25-b0a7-71ad7608784d)
![246843060 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/1f058aaf-2734-48e4-af0e-b92610c64ab9)
![246843060 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/2a256621-4904-490d-b042-fe9839bb1aed)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Nice

**Comment by grd349** [comment]
Yes.
