### ISSUE TITLE
EPIC 248424564 (The Chosen One)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#57]
![248424564 - 14 - MS - Echelle](https://github.com/user-attachments/assets/884f7ff7-78ea-4f04-b2e4-8da13002e643)
![248424564 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/b89b7dfa-ccdf-4713-bd55-c3837beff41e)
![248424564 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/8bb08049-e00c-471f-a0ac-ac4e886f3b2d)
![248424564 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/543d472d-1edd-4a1e-9366-cf802bd2cea8)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Nice
