### ISSUE TITLE
EPIC 248729983 (Bofur)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#58]
![248729983 - 14 - MS - Echelle](https://github.com/user-attachments/assets/36c328e7-946f-4e4c-8b33-2c93e7475f6b)
![248729983 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/a8b9650d-639b-4767-a309-0e5fc69d2e96)
![248729983 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c9adbf6d-a2be-4dbc-b841-f268c790c7d6)
![248729983 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/0c731cd7-5c4c-4f5c-b7aa-e9f8d3757d5a)

@nielsenmb @grd349

**Comment by grd349** [comment]
Love it.

**Comment by nielsenmb** [comment]
Yeah, this one looks good.
