### ISSUE TITLE
EPIC 249151042 (Bombur)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#59]
![249151042 - 14 - MS - Echelle](https://github.com/user-attachments/assets/d65c025f-ec39-458d-bafc-302ca0a34f7b)
![249151042 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/f60a42ca-8a24-488c-8755-2e168c1e9e9a)
![249151042 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/00eff44b-46d6-44ce-a5ec-2cb4e0d1793b)
![249151042 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/6ab84a80-2f23-4fd6-b495-4aa241faa4f1)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Do you think this one's worth trying as a sub-giant?

**Comment by grd349** [comment]
It could be that this is an example of curvature that is more extreme than we are use to.  The l=0 ridge seems to support this although it is marginal.

**Comment by George-Hookway** [comment]
I tried it as a subgiant and nothing of note came out of it.

I feel this one could be considered completed
