### ISSUE TITLE
EPIC 246685193 (Bluey)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#6]
![246685193 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/90e3603d-28aa-4941-bbb7-cb2ac570cd61)
![246685193 - 10 - MS - Frequency Range](https://github.com/user-attachments/assets/6ad502ad-2176-4113-8b3a-01d4c7b00aad)
![246685193 - 10 - MS - Echelle](https://github.com/user-attachments/assets/87c99c1f-170f-40d7-ac04-44b3f060ec1d)
![246685193 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/28335ec0-b07f-41f0-9dfc-3e14de0b4e97)
![246685193 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/f9e085e0-5460-4cb6-a563-849fa3a1c634)

@nielsenmb @grd349

**Comment by grd349** [comment]
Glorious!

**Comment by nielsenmb** [comment]
All good!
