### ISSUE TITLE
EPIC 249200379 (Meriadoc Brandybuck)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#60]
![249200379 - 14 - MS - Echelle](https://github.com/user-attachments/assets/22ba1b0d-8966-455c-9270-3cf60dcbce01)
![249200379 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/a57110d7-1b6d-410a-afb9-a414cb8ad7a7)
![249200379 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/82df8547-d7b5-4b7c-8889-ead4f101a36e)
![249200379 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/9b5194d0-ac4d-4dc8-8096-17d1963f36c7)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Probably OK. Just double check epsilon.

**Comment by George-Hookway** [comment]
Epsilon here was 1.24, which was expected

**Comment by grd349** [comment]
Wait - are there two humps here? Is this an asteroseismic binary?

**Comment by grd349** [comment]
@nielsenmb ? :)

**Comment by nielsenmb** [comment]
You're thinking that dent in the power at ~1800? I think that's just realization noise. 

Also the ratio of the mode heights would be wrong, lower frequency should be the higher one no?

**Comment by nielsenmb** [comment]
https://simbad.u-strasbg.fr/simbad/sim-coo?Coord=15%3A33%3A59.692+-25%3A40%3A15.47&CooFrame=FK5&CooEpoch=2000&CooEqui=2000&CooDefinedFrames=none&Radius=2&Radius.unit=arcmin&submit=submit+query&CoordList=

**Comment by nielsenmb** [comment]
Apparently there isn't any spectroscopy in the eso archive, just some broadband photometry. Doesn't mean it doesn't exist, but it'll just be harder to find.

**Comment by grd349** [comment]
Maybe a SONG application for some RV's.  Or speak to the planet people about getting help getting RVs.

**Comment by nielsenmb** [comment]
Yeah, they'll probably know some good places to search. If only there was a central repository for all astronomy data....

**Comment by grd349** [comment]
I have spoken to Mikkel about this.  He has had a look and agrees with the second signal and that it is probably an asteroseismic binary. He was not aware of this system being interesting. 

If we can do some analysis that really demonstrates the second signal, we can add this system to his NOT proposal for RV follow-up of seismic binaries.

**Comment by nielsenmb** [comment]
![image](https://github.com/user-attachments/assets/dd369fcd-65e0-4b19-8cd2-a47a0df2f438)

**Comment by George-Hookway** [comment]
I'll mark Merry as completed, since the envelopes don't overlap too much.
