### ISSUE TITLE
EPIC 249404897 (Gandalf the Grey)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#61]
![249404897 - 14 - MS - Echelle](https://github.com/user-attachments/assets/1fc8b1b1-5721-4fab-849a-e4a8c300067d)
![249404897 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/7e325245-31d2-41d0-adc1-2fbb26206d93)
![249404897 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/cad212a0-3e76-4e6c-bef3-50b4ebb6905a)
![249404897 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/27da8c30-b92a-4b9c-a0c6-afbde4e625a1)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Yup

**Comment by grd349** [comment]
Boom
