### ISSUE TITLE
EPIC 249620304 (Frodo Baggins)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#62]
![249620304 - 14 - MS - Echelle](https://github.com/user-attachments/assets/012a6554-18fb-4b54-bd30-c4c732e922a0)
![249620304 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/df5bff2f-0295-4b56-a132-958ce344eb05)
![249620304 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/148285c5-924a-44b2-b175-0f923bf846d5)
![249620304 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/ffee03d9-fe75-4a86-9e55-31cc90956d4a)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Is the strong l=1 mode at high frequencies noise, rather than a correct identification?

**Comment by nielsenmb** [comment]
Yeah I think the mode ID is good, but the peakbag stage has a bit too much freedom to move around, so it jumps over to the big peak. 

It's definitely not a mode, so it's gotta be a systematic of some sort. Check the readme maybe? 

Maybe we add this to the list of stars we ask Mikkel about.

**Comment by George-Hookway** [comment]
![249620304 - 12 - MS - Echelle](https://github.com/user-attachments/assets/2a31eba2-7bd1-45ac-8b38-6b324ea59e83)
![249620304 - 12 - MS - Mode ID](https://github.com/user-attachments/assets/15ed2a1f-a066-47b0-955c-5d17b0008769)
![249620304 - 12 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/aa2b70c1-4e22-4256-9f10-08d512c40c39)
![249620304 - 12 - MS - Peakbagging](https://github.com/user-attachments/assets/a3b88662-4c2d-4251-a2f2-8a6938ec3fd1)

**Comment by nielsenmb** [comment]
Very nice!
