### ISSUE TITLE
EPIC 249790971 (Samwise the Brave)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#63]
![249790971 - 14 - MS - Echelle](https://github.com/user-attachments/assets/63450d1b-124d-4546-bacc-5d7a6ebd44de)
![249790971 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/0042edd7-cfc2-4f81-afc2-99db90a2014f)
![249790971 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/f888bb25-4ab0-4a0b-9788-29476d249f47)
![249790971 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/e3c789f0-fdad-4d1c-95ad-cb4bd13bebd0)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
I'm now more and more confident that if there's some funkyness at ~2100, it's systematic. 

Looks good though! Happy that it ignored that bump in power.

**Comment by grd349** [comment]
All good for me!
