### ISSUE TITLE
EPIC 249810309 (Merry)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#64]
![249810309 - 14 - MS - Echelle](https://github.com/user-attachments/assets/a9132dcb-793e-4238-a7e9-051e01e92837)
![249810309 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/708e0d98-8e4f-4ac9-be09-9f9a4cc6fdf3)
![249810309 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/a89d834b-5869-41f2-bb3c-5fa1683cc0e8)
![249810309 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/3665f0f5-7c28-46fb-b022-09546f9791d9)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
nice!

**Comment by grd349** [comment]
Beautiful!
