### ISSUE TITLE
EPIC 212487676 (Aragorn, son of Arathorn)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#65]
![212487676 - 14 - MS - Echelle](https://github.com/user-attachments/assets/a205659e-8097-4dbd-b14a-4a19a5a77a89)
![212487676 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/00e2ed40-bd6f-4247-a89a-54533c548361)
![212487676 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/4b3de92a-bfdf-4bea-8c93-2efac34fd669)
![212487676 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/051959b0-8061-487a-a32a-3173cc02d0cd)

@nielsenmb @grd349

**Comment by grd349** [comment]
Stunning

**Comment by George-Hookway** [comment]
@nielsenmb ?

**Comment by nielsenmb** [comment]
Yep.
