### ISSUE TITLE
EPIC 212509747 (Gimli, son of Gloin)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#66]
![212509747 - 15 - MS - Echelle](https://github.com/user-attachments/assets/64e15e8d-1543-40cb-b8a1-f3305fa425e7)
![212509747 - 15 - MS - Mode ID](https://github.com/user-attachments/assets/bd0d354a-2f1b-4051-9a37-c5c7b04c9d62)
![212509747 - 15 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/805cbcb7-e5c8-412b-8c76-b2cc8c4782b0)
![212509747 - 15 - MS - Peakbagging](https://github.com/user-attachments/assets/0b291a3e-e93e-4330-959d-970e8ea80703)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
![212509747 - 19 - MS - Echelle](https://github.com/user-attachments/assets/9d61f642-d973-45ca-9670-2b767754bdcd)
![212509747 - 19 - MS - Mode ID](https://github.com/user-attachments/assets/f5adae8f-a715-41d9-b97e-b39f5267b1f1)
![212509747 - 19 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/5fbe27a2-fe7a-4e92-aa47-8f6de1bcf26a)
![212509747 - 19 - MS - Peakbagging](https://github.com/user-attachments/assets/86646ca6-c223-4096-84d8-284fe7f29dc1)

**Comment by George-Hookway** [comment]
I increased it to Np=19. Is it a concern that the echelles show a slight discontinuity at either end of the higher power modes in the centre?

**Comment by grd349** [comment]
> Is it a concern that the echelles show a slight discontinuity at either end of the higher power modes in the centre?

Maybe - maybe not. This could be due to the signature of the Helium II ionisation zone and even the base of the convection zone.  (and even the Helium I ionisation).  These things cause 'glitches' in the otherwise smooth asymptotic prescription. 

I think the final peak bag model looks good, so I suspect these features are real and due to glitches.

**Comment by nielsenmb** [comment]
The low frequency one could be an avoided crossing. Given the numax and Teff of this target it seems a bit unlikely, but the high Np is pushing the model really far down in frequency.

Regardless the solution is good though, so it's up to the modelers what it means.
