### ISSUE TITLE
EPIC 212624487 (Legolas, of the Woodland Realm)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#67]
![212624487 - 14 - MS - Echelle](https://github.com/user-attachments/assets/8eeb1e0e-1a2e-4669-8e18-75a17edeaef4)
![212624487 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/5114b3a5-fdc0-48f1-9fe8-558e7b40a6fa)
![212624487 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/e49d2705-16bb-41e6-a4cc-317b3fb65810)
![212624487 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/3cc4413c-f6f0-4180-90ea-c3ca36efbd84)

@nielsenmb @grd349

**Comment by grd349** [comment]
Good enough I think.

**Comment by George-Hookway** [comment]
@nielsenmb ?

**Comment by nielsenmb** [comment]
Looks good!
