### ISSUE TITLE
EPIC 226464131 (Boromir)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#68]
![226464131 - 14 - MS - Echelle](https://github.com/user-attachments/assets/eef09e65-adda-4b5f-80dc-04e8adb888d6)
![226464131 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/d0a7b86e-7611-458a-aedb-f50f28b8a51a)
![226464131 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/60184452-bf7a-4102-8f45-642aebd6b5b6)
![226464131 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/2a28f460-ab2d-4265-bcc1-bc1dea2bf2b8)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks OK to me. Not a great one though.

**Comment by grd349** [comment]
I'll take this!
