### ISSUE TITLE
EPIC 246033065 (Outer Wilds)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#69]

**Comment by George-Hookway** [comment]
![246033065 - 14 - MS - Echelle](https://github.com/user-attachments/assets/55c7c113-67c0-47a3-8b6b-f87b97681f22)
![246033065 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/e857c18f-3a64-41a5-87bc-10387ba7b135)
![246033065 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/8bf8f6cb-3b36-4c58-a281-be46e024f9d8)
![246033065 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/6a48ae73-a172-4cd3-a2a9-c1880ebf8cc5)

@nielsenmb @grd349

**Comment by grd349** [comment]
Yep

**Comment by nielsenmb** [comment]
Nice.
