### ISSUE TITLE
EPIC 212053807 (Bill the Pony)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#71]

**Comment by George-Hookway** [comment]
![212053807 - 14 - MS - Echelle](https://github.com/user-attachments/assets/94ccbe63-19b9-4e6d-b91c-3a1927395787)
![212053807 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/858f188c-be14-40a3-9dc1-871913706398)
![212053807 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/a2d652d3-6e46-404f-b95e-bef50df7018c)
![212053807 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/703ce1d5-dc86-4ca9-8f15-382e2c6b9c68)

@nielsenmb @grd349

**Comment by grd349** [comment]
It's a yes from me.

**Comment by nielsenmb** [comment]
yup
