### ISSUE TITLE
EPIC 248785352 (Brittle Hollow)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#72]
![248785352 - 14 - MS - Echelle](https://github.com/user-attachments/assets/9c79cdd3-1f6a-42a3-a16c-b3f2bcf0cfa7)
![248785352 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/9ba8e4aa-8a8e-472d-8ae6-a2f678778a04)
![248785352 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/b9e97285-85a6-47f4-b611-88f3e8e1ad47)
![248785352 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/4909101e-249e-426a-a77d-5d63a1a386be)

@nielsenmb @grd349

**Comment by grd349** [comment]
Oh yes!

**Comment by nielsenmb** [comment]
Yep.

I'm seeing the same structure at low frequency as with Merry, so it's probably not a planet :(
