### ISSUE TITLE
EPIC 250141301 (Dark Bramble)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#74]
![250141301 - 14 - MS - Echelle](https://github.com/user-attachments/assets/0a8a4aa7-b945-40e1-b9f9-c1fd427770b6)
![250141301 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/7d5fa58c-fab0-4737-9bde-d3d218e13c25)
![250141301 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/e392505e-183d-40e9-84c3-d534b49e1de2)
![250141301 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/61a7ca2f-5805-4e90-aa4f-9e0f6ef5b80b)

@nielsenmb @grd349

**Comment by grd349** [comment]
Yes!

**Comment by nielsenmb** [comment]
Nice.
