### ISSUE TITLE
EPIC 212485100 (The Eye of the Universe)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#75]
![212485100 - 18 - MS - Echelle](https://github.com/user-attachments/assets/3a20e876-10f1-4d87-8f6d-9a042b4e9cc0)
![212485100 - 18 - MS - Mode ID](https://github.com/user-attachments/assets/32d8c9b1-069b-4b56-a8ff-e33852636e36)
![212485100 - 18 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c1d9f6de-bf59-46f0-bcc8-dc022111d5c6)
![212485100 - 18 - MS - Peakbagging](https://github.com/user-attachments/assets/f9f57c3e-0262-4770-8918-d13bf27f61dc)

@nielsenmb @grd349

**Comment by grd349** [comment]
Is there anything more in terms of signal to be had at high frequency?  I guess not, but I thought I'd ask.

**Comment by George-Hookway** [comment]
My instinct is that there's just noise, but I can run it anyway just in case.

**Comment by grd349** [comment]
> My instinct is that there's just noise, but I can run it anyway just in case.

Your call - choose wisely ;)

**Comment by George-Hookway** [comment]
![212485100 - 20 - MS - Echelle](https://github.com/user-attachments/assets/65526d12-92d6-4ef8-a9e7-310bc9e18c94)
![212485100 - 20 - MS - Mode ID](https://github.com/user-attachments/assets/5c0da5c3-233e-4dfd-8a39-28c7a0408db6)
![212485100 - 20 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/3f288aad-a324-4bbb-9a73-9cfb1643ae12)
![212485100 - 20 - MS - Peakbagging](https://github.com/user-attachments/assets/c1650407-36af-4e64-b0d7-b9f2ab876f16)

**Comment by nielsenmb** [comment]
Looks good!

**Comment by grd349** [comment]
Looks good to me.
