### ISSUE TITLE
EPIC 233947029 (Chert)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#76]
![233947029 - 16 - MS - Echelle](https://github.com/user-attachments/assets/083ea05a-6b78-4421-b3dd-6efa8f6daed7)
![233947029 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/47779624-8373-4837-b295-efb74fa2a27a)
![233947029 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/7ddd7204-ea29-44df-be86-4913a01cfdc9)
![233947029 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/24f83814-8871-47cc-b0c3-2da5bcb2be14)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Perhaps I'm looking for things that aren't there now, after all the excitement with Merry, but is there are smaller peak at ~1100 microHz?

**Comment by grd349** [comment]
> Perhaps I'm looking for things that aren't there now, after all the excitement with Merry, but is there are smaller peak at ~1100 microHz?

It's always worth looking.  Here I think there are a lot of systematic peaks.  The peaks look like they could be from a transit or eclipse and it might be worth checking but most likely a signal this big is well known.

**Comment by nielsenmb** [comment]
I would actually limit the model to exclude those peaks. You can see the l=0 mode in the peakbag stage moves to include one of them.

You can do this by doing freqLimit=[1250, 2150] or something like that.

**Comment by George-Hookway** [comment]
![233947029 - 10 - MS - Echelle](https://github.com/user-attachments/assets/a3788fa2-019e-45b8-96a3-974a7c5845f5)
![233947029 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/ee3d9999-591c-4411-a815-f7f55049ac3b)
![233947029 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/2ad82d50-cb73-488f-9b28-2a6b9cc3a11c)
![233947029 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/5341dd59-31e4-4cd2-8094-16300113264a)
