### ISSUE TITLE
EPIC 236344582 (Slate)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#77]
![236344582 - 16 - MS - Echelle](https://github.com/user-attachments/assets/0cc52d10-b759-41e6-8489-85c94cad4c5b)
![236344582 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/8b09ca78-fa15-435d-8b30-944f008b293d)
![236344582 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/436bc4cf-5a77-4164-aa1a-ea64394ad23f)
![236344582 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/b05a80b8-d7e0-41e9-b721-8ce7a9e5144b)

@nielsenmb @grd349

**Comment by grd349** [comment]
Oh yes.

**Comment by nielsenmb** [comment]
Nice
