### ISSUE TITLE
EPIC 249869231 (Millennium Falcon)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#78]
![249869231 - 16 - MS - Echelle](https://github.com/user-attachments/assets/f18097ed-9f0d-40ae-9ab3-ad2bc7db4d89)
![249869231 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/f4fe625c-9e06-4408-b38c-b4018123fb1c)
![249869231 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/c7389899-393f-4716-b11d-4330969aed42)
![249869231 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/27fb3cdc-8ec4-40ee-926d-d1c54b8b53b2)

@nielsenmb @grd349

**Comment by grd349** [comment]
There is something strange about this one. Let's discuss in the meeting.

**Comment by nielsenmb** [comment]
The clumpyness around 1000?

**Comment by grd349** [comment]
Actually, I think I am probably ok with this one as long as epsilon matches.

**Comment by George-Hookway** [comment]
Using epsilon of 0.9971805412788679
Model suggests 0.9159540000000002

This matches pretty well, so I think we're alright here.
