### ISSUE TITLE
EPIC 250165973 (Gallifrey)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#79]
![250165973 - 16 - MS - Echelle](https://github.com/user-attachments/assets/075b64c4-c424-4172-aae1-25b7d0b052d8)
![250165973 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/740c1b0e-ce4c-4942-965e-8bda7f4e4b90)
![250165973 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/4c99a6f6-8848-4d32-9113-b63e0bcce68f)
![250165973 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/2adbd070-37bf-4cc0-b86b-0f3f9adb87b2)

@nielsenmb @grd349

**Comment by grd349** [comment]
Epic!

**Comment by nielsenmb** [comment]
nice!
