### ISSUE TITLE
EPIC 226083290 (The Other One)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#8]
The Mode ID's a bit weird, but it seems to be alright in the end.

![226083290 - 9 - MS - Mode ID](https://github.com/user-attachments/assets/3b740c76-f1ae-4e7b-9480-e3a195b531e1)
![226083290 - 9 - MS - Echelle](https://github.com/user-attachments/assets/95873d89-5beb-4f3c-ac2a-a2c9f73ffb8c)
![226083290 - 9 - MS - Frequency Range](https://github.com/user-attachments/assets/f8b71732-7044-44e3-bf8b-46df42d521fe)
![226083290 - 9 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/ba65719b-aa08-4ea1-8844-105b5601d06d)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
I'm leaning toward this being correct, hard to say either way, at this numax if epsilon_p ~ 1.4 then it's probably the right ID.

Again it seems like the model isn't stretching up in frequency far enough, which suggests the input numax is too small by 1 dnu or so.

**Comment by George-Hookway** [comment]
Keystone numax is ~2400, but the mode ID and peakbag makes it look closer to ~2200, which would suggest numax should be even lower.

**Comment by nielsenmb** [comment]
Oh, my bad, it was looking at the peakbag model range, which seems to stretch quite far down. The mode ID input numax does indeed look to large as you say.

**Comment by George-Hookway** [comment]
![226083290 - 10 - MS - Echelle](https://github.com/user-attachments/assets/79be0754-44cc-4fce-b560-e22f3d3ca978)
![226083290 - 10 - MS - Mode ID](https://github.com/user-attachments/assets/1b473180-a1c3-4e7e-8d29-310dd5ac3c43)
![226083290 - 10 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/fae532b1-b6cb-462d-9667-725624ef5a81)
![226083290 - 10 - MS - Peakbagging](https://github.com/user-attachments/assets/7d8d865e-65f7-469b-9230-69469ac07e92)

**Comment by grd349** [comment]
Looks good to me!

**Comment by nielsenmb** [comment]
The initial numax looks a bit weird, but other the mode ID and final result look good.

**Comment by George-Hookway** [comment]
PBjam does tend to lower the input numax, this one by ~200 microHz. I suspect that this is the issue for a number of stars.

**Comment by nielsenmb** [comment]
Might be a systematic problem with the method they used to estimate it in the K2 paper. The modes are wider at higher frequency, so can be clearer than the low frequency modes, so it might skew numax upward. 

I'd say in this case PBjam is getting the right numax though.

**Comment by George-Hookway** [comment]
Yep, I agree with PBjam's assessment most of the time
