### ISSUE TITLE
EPIC 212516207 (Gossan)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#80]
![212516207 - 18 - MS - Echelle](https://github.com/user-attachments/assets/c8c1360d-4ebb-4a68-a796-096e891295fb)
![212516207 - 18 - MS - Mode ID](https://github.com/user-attachments/assets/efd0b772-047b-4338-b95a-068e2f43771e)
![212516207 - 18 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/b661f872-eef7-4f00-b37a-855b23572c51)
![212516207 - 18 - MS - Peakbagging](https://github.com/user-attachments/assets/514d13ff-b2e8-482f-b65a-1e01f45eed0f)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
bit too many orders on this one, but results look fine otherwise.

**Comment by grd349** [comment]
Looks ok to me!
