### ISSUE TITLE
EPIC 215035735 (Hornfels)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#81]
![215035735 - 18 - MS - Echelle](https://github.com/user-attachments/assets/10da7858-dd9f-4624-9a55-68f723dfed2e)
![215035735 - 18 - MS - Mode ID](https://github.com/user-attachments/assets/c5764158-5e5d-4713-83ae-60ef7786e1c5)
![215035735 - 18 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/0f8ccfdd-58bf-4074-8c47-26f6df9438b7)
![215035735 - 18 - MS - Peakbagging](https://github.com/user-attachments/assets/7cc48f2c-e2d9-4c49-accb-33c1102633d9)

@nielsenmb @grd349

**Comment by grd349** [comment]
That'll do!

**Comment by nielsenmb** [comment]
Yup
