### ISSUE TITLE
EPIC 228704734 (Hal)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#82]
![228704734 - 17 - MS - Echelle](https://github.com/user-attachments/assets/bed48dbf-e0e2-40a2-81a0-0bf89550ee48)
![228704734 - 17 - MS - Mode ID](https://github.com/user-attachments/assets/dd371e43-b9bb-42df-91ca-25c500ae1c3d)
![228704734 - 17 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/a6dfe141-1fe5-4e69-a8c3-8f5260399657)
![228704734 - 17 - MS - Peakbagging](https://github.com/user-attachments/assets/1666807d-3d9f-4edb-9068-6e4e617e06aa)

@nielsenmb @grd349

**Comment by grd349** [comment]
I guess.  I'm a little worried about how the l=0 near numax jumps to the right but I suspect that is what the data says.

**Comment by George-Hookway** [comment]
The l=1 modes follow a similar pattern at around the same frequency, though not as extreme.

**Comment by nielsenmb** [comment]
Yeah, not much that can be corrected here. I'm going to guess the uncertainties are also going to be larger because of this effect.
