### ISSUE TITLE
EPIC 234863731 (Esker)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#83]
![234863731 - 16 - MS - Echelle](https://github.com/user-attachments/assets/4a0469f4-b052-49f9-87b2-d8dc62c7b957)
![234863731 - 16 - MS - Mode ID](https://github.com/user-attachments/assets/336cfdaf-0a9d-4459-94b3-2bee9024949c)
![234863731 - 16 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/4ee69a72-a300-4a94-956d-38b1da3a2ac0)
![234863731 - 16 - MS - Peakbagging](https://github.com/user-attachments/assets/11f792a8-f403-4056-a468-62978a475b63)

@nielsenmb @grd349

**Comment by grd349** [comment]
yeah - i think that is ok.

**Comment by nielsenmb** [comment]
yup. Again not such a clear granulation signature on this one :/
