### ISSUE TITLE
EPIC 212709737 (Mittens)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#84]
![212709737 - 19 - MS - Echelle](https://github.com/user-attachments/assets/4f1f88d0-260b-497f-b211-a935071bd7ac)
![212709737 - 19 - MS - Mode ID](https://github.com/user-attachments/assets/4d133862-b25d-4b10-bcaf-559bd092e861)
![212709737 - 19 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/8d436637-82be-4800-9e1b-21a422e91042)
![212709737 - 19 - MS - Peakbagging](https://github.com/user-attachments/assets/d631eb39-181d-4163-8d2a-1613b042a414)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Hmmmm...OK I guess, but hard to be sure.

**Comment by grd349** [comment]
Yeah this one is tricky - I guess we are reliant on epsilon.

**Comment by grd349** [comment]
@George-Hookway @nielsenmb This is a binary.  It is also probably an asteroseismic binary.  We should re process. 

Mikkel will be asked to make new lightcurves - @rgarcibus . Wait for Mikkel to do the lightcurve.

**Comment by grd349** [comment]
@George-Hookway New name require for the binary.
