### ISSUE TITLE
EPIC 212636554 (Mimi)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#85]
![212636554 - 21 - MS - Echelle](https://github.com/user-attachments/assets/9a7a5cea-6dc9-4815-a0b6-ad35085c0217)
![212636554 - 21 - MS - Mode ID](https://github.com/user-attachments/assets/a6fe4c37-fa05-4779-aa37-0a1b2a89f9b4)
![212636554 - 21 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/131ae065-6a0d-4072-85be-51d69198313d)
![212636554 - 21 - MS - Peakbagging](https://github.com/user-attachments/assets/606ded73-5aca-410a-9e44-d4f972457995)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Bit too many radial orders on this one I think. The end result looks fine though, most of the modes probably just reflect the prior, so we don't really learn much.

**Comment by grd349** [comment]
I think I can cope with this.
