### ISSUE TITLE
EPIC 201644284 (Maisy)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#86]
![201644284 - 8 - SG - Echelle](https://github.com/user-attachments/assets/5a836664-4d5b-42b8-9e20-66b4a5a7d402)
![201644284 - 8 - SG - Mode ID](https://github.com/user-attachments/assets/082a2a78-e432-41a3-8289-c9d20fefff9d)
![201644284 - 8 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/58850c66-207a-4fe2-833c-252c90a8a1c5)
![201644284 - 8 - SG - Peakbagging](https://github.com/user-attachments/assets/66c8312a-7c9c-4cd4-870e-91d856a7317b)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Final result looks good. Definitely needs some pruning though. 

Might be a good case to test the KS-test algorithm on.

**Comment by grd349** [comment]
Good for me!
