### ISSUE TITLE
EPIC 201725213 (Daisy)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#87]
![201725213 - 8 - SG - Echelle](https://github.com/user-attachments/assets/e23efbbc-3899-4e55-89bf-603895dee852)
![201725213 - 8 - SG - Mode ID](https://github.com/user-attachments/assets/4801c000-86b7-4ab3-b823-cb0da481160a)
![201725213 - 8 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/3c05cfff-52a2-4627-894a-7ea0675b5680)
![201725213 - 8 - SG - Peakbagging](https://github.com/user-attachments/assets/6c0b6ee2-6ada-413c-8467-fc3abc03403d)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Takes a bit of effort to confirm things, but it doesn't look too bad actually. There's a relatively high power mode at ~710muHz which isn't picked up by the l=1 model. 

The l=2 is bumped slightly to higher frequency, so it might be a mixed l=2?

**Comment by grd349** [comment]
Looks pretty good to me - I suspect the 710 muHz mode is a bumped l=2.
