### ISSUE TITLE
EPIC 211506655 (Abi)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#89]
![211506655 - 8 - SG - Echelle](https://github.com/user-attachments/assets/a82d4d38-b4e4-47da-b5d5-99875e616a24)
![211506655 - 8 - SG - Mode ID](https://github.com/user-attachments/assets/9a6eea63-f78d-4c55-ab04-9a3c6cc7b67f)
![211506655 - 8 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/2a900ae4-3938-42a3-883d-d39fa9630f3a)
![211506655 - 8 - SG - Peakbagging](https://github.com/user-attachments/assets/193a2aaa-238f-4c05-8f09-56db34e60e55)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Since this seems to be a red giant, is it worth re-running with the RGB model?

**Comment by nielsenmb** [comment]
I would definitely be interested in seeing the result!

I think the final peakbag plot also need some tweaking.

**Comment by grd349** [comment]
Doesn't look too bad to me but I'll defer to Martin.

**Comment by George-Hookway** [comment]
![211506655 - 9 - RGB - Echelle](https://github.com/user-attachments/assets/5f95628d-ac6e-4087-9a2e-f4e56a1bc2f1)
![211506655 - 9 - RGB - Mode ID](https://github.com/user-attachments/assets/5f2b4a09-af38-4ffc-a57f-723de4141eda)
![211506655 - 9 - RGB - Peakbagged Echelle](https://github.com/user-attachments/assets/d51c69ee-9207-44eb-99e3-cc9ae45bda77)
![211506655 - 9 - RGB - Peakbagging](https://github.com/user-attachments/assets/31bbf123-ce8d-49e4-a8f1-8d79b29a6fda)

**Comment by George-Hookway** [comment]
I re-ran as a red giant and the results are largely the same.

When removing systematics, one of the l=0 modes was removed, and PBjam's placed an l=1 there instead. Since we know there should be a peak there, would it be wise to just leave that systematic in, especially since it's power would be small compared to the actually mode at this SNR?

**Comment by grd349** [comment]
This is amazing!

**Comment by nielsenmb** [comment]
Very nice! Amazed it worked so well with the RG model.

**Comment by George-Hookway** [comment]
![211506655 - 8 - SG - Echelle](https://github.com/user-attachments/assets/26d58e7f-f398-4533-980d-01f2ec0ff653)
![211506655 - 8 - SG - Mode ID](https://github.com/user-attachments/assets/16a51316-5662-44ba-8cc4-8edb98d764ab)
![211506655 - 8 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/11105a13-8e90-4d6c-8f84-b34023ff34bf)
![211506655 - 8 - SG - Peakbagging](https://github.com/user-attachments/assets/6ed39742-7414-4b2d-8345-2c5d5ffdf29c)

**Comment by George-Hookway** [comment]
This is with the sub-giant model. The SG model seems to provide slightly better Mode IDs, so I've used it instead, since this star is on the boundary.

**Comment by grd349** [comment]
Awesome!

**Comment by nielsenmb** [comment]
Looks alright to me.

Looks like we need those l=3 modes though :)
