### ISSUE TITLE
EPIC 211311380 (William)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#9]
![211311380 - 14 - MS - Echelle](https://github.com/user-attachments/assets/2eebc190-f633-4765-9f04-cd105963d7c6)
![211311380 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/d5ce816f-ddc7-4aca-a3bc-f3c67e41a935)
![211311380 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/9efa208b-3124-4fe8-9a34-828469fd4eb8)
![211311380 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/1014008d-43f8-4547-9f77-80b690e0e689)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Feel free to create an issue and submit a PR to fix it! :)

**Comment by nielsenmb** [comment]
oh, and this looks good to me too. There's a cluster of peaks at ~2400muHz which initially looked like a 2,0 to me, but it doesn't quite fit, so maybe it's just the realization.
