### ISSUE TITLE
EPIC 212478598 (Merlin)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#90]
![212478598 - 8 - SG - Echelle](https://github.com/user-attachments/assets/a29f3dc3-3e3f-4af8-983a-9b04e806d167)
![212478598 - 8 - SG - Mode ID](https://github.com/user-attachments/assets/a78a1637-f436-42df-8b52-8c5c98d5cd37)
![212478598 - 8 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/eefbfcf6-372e-48a2-b63e-319d5ac9ea78)
![212478598 - 8 - SG - Peakbagging](https://github.com/user-attachments/assets/a64abde3-48ae-41f9-84cb-0dd6377b3c90)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Wow, not bad...

This is right at the edge I'd say. I'd be interested to see if the RG model works for this one. If it does it could be a good place to make a cut between the two models if it generally works for things below 500-550 for example.

**Comment by grd349** [comment]
Looks pretty good to me - do we need to worry about the systematics?

**Comment by George-Hookway** [comment]
Probably. There are other stars that suffer significantly from it, so I'll deal with it now.
