### ISSUE TITLE
EPIC 228739655 (Riebeck)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#91]
![228739655 - 8 - SG - Echelle](https://github.com/user-attachments/assets/6f1b0a31-9edd-41d0-863b-526044a438a7)
![228739655 - 8 - SG - Mode ID](https://github.com/user-attachments/assets/917bfa37-d591-4148-95c9-1d9673d6b823)
![228739655 - 8 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/f25ba13e-bdca-4d2f-895a-65afdf9ad1a8)
![228739655 - 8 - SG - Peakbagging](https://github.com/user-attachments/assets/a0431d28-3226-4cb9-8108-d56c3a73c78e)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks very nice to me.

**Comment by grd349** [comment]
Sold!
