### ISSUE TITLE
EPIC 233933903 (Whiskers)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#92]
![233933903 - 14 - MS - Echelle](https://github.com/user-attachments/assets/51d50ea2-8734-46ec-9d4e-793e4227dce8)
![233933903 - 14 - MS - Mode ID](https://github.com/user-attachments/assets/88361cc8-3ce5-457e-8a80-28f498dc0d51)
![233933903 - 14 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/42361228-9fd2-4563-a0d2-dbe8bf95f416)
![233933903 - 14 - MS - Peakbagging](https://github.com/user-attachments/assets/c8e47072-39fd-4d77-974d-5a89357167a1)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
This is the first star cured of the 'dodgy epsilon' disease. I reduced the Teff from 5811K --> 5704K and it seems to have corrected epsilon.

**Comment by nielsenmb** [comment]
Nice!

**Comment by George-Hookway** [comment]
I just took it from Gaia

**Comment by grd349** [comment]
That's great!  I think there are additional modes at high frequency - can we try and grab them?

**Comment by George-Hookway** [comment]
Yep, I'm running it now

**Comment by George-Hookway** [comment]
I increased Np to 15, and it got largely the same result, though the Mode ID got a tad bit confused.

**Comment by grd349** [comment]
I'm happy here!
