### ISSUE TITLE
EPIC 212683142 (Feldspar)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#95]
![212683142 - 11 - SG - Echelle](https://github.com/user-attachments/assets/1e4c5ab5-e0b6-412c-b760-b2481d1de9c0)
![212683142 - 11 - SG - Mode ID](https://github.com/user-attachments/assets/607c1f75-1d49-472b-89cb-f5a196a5af11)
![212683142 - 11 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/dd32002a-6cd1-4679-a35d-3ce1127c1dca)
![212683142 - 11 - SG - Peakbagging](https://github.com/user-attachments/assets/66ee5fa5-bf20-41bb-93b7-ed13efa49a91)

@nielsenmb @grd349

**Comment by George-Hookway** [comment]
Is this another case of ng=1 being in the wrong place?

**Comment by grd349** [comment]
This looks good to me - have we talked about rotational splitting yet?

**Comment by George-Hookway** [comment]
Is this what can cause the splitting of the modes?

**Comment by nielsenmb** [comment]
Hmm, hard to say with this one where ng=1 should be. I don't think it's inconceivable that it could appear above the envelope, but I think I would tend toward it being not being so.

End result looks great though.

**Comment by George-Hookway** [comment]
Should we be concerned about the g-modes not being correctly identified, or is it fine as is?

**Comment by nielsenmb** [comment]
In this particular case it's probably fine.

However, this wouldn't be suitable for including in the prior.
