### ISSUE TITLE
EPIC 212305951 (The Interloper)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#96]
![212305951 - 11 - MS - Echelle](https://github.com/user-attachments/assets/935447b9-c542-4fa4-b814-5069bffd8aea)
![212305951 - 11 - MS - Mode ID](https://github.com/user-attachments/assets/17768ed1-0812-4ef3-9cd5-6cf317a7ced8)
![212305951 - 11 - MS - Peakbagged Echelle](https://github.com/user-attachments/assets/794dbb56-2f03-4802-8929-356e5f9f04f4)
![212305951 - 11 - MS - Peakbagging](https://github.com/user-attachments/assets/48db6dbb-54a1-4f0e-b6e3-a38fb12caf24)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Look OK to me.

**Comment by George-Hookway** [comment]
Does @grd349 approve?

**Comment by grd349** [comment]
I agree if epsilon agrees.
