### ISSUE TITLE
EPIC 228737206 (The Prisoner)

### ISSUE THREAD

**Issue by George-Hookway** [George-Hookway/PBjammy#99]
![228737206 - 9 - SG - Echelle](https://github.com/user-attachments/assets/b45cd164-1bba-4450-a4f8-ec53cb5c69c2)
![228737206 - 9 - SG - Mode ID](https://github.com/user-attachments/assets/9fb19da1-8d3a-49ad-8201-64ee5585b262)
![228737206 - 9 - SG - Peakbagged Echelle](https://github.com/user-attachments/assets/5fb140b2-bfc7-49d7-b474-b7b2b1fdd960)
![228737206 - 9 - SG - Peakbagging](https://github.com/user-attachments/assets/fe816c67-3356-4017-b218-9fe8220c6b4e)

@nielsenmb @grd349

**Comment by nielsenmb** [comment]
Looks alright to me.

**Comment by grd349** [comment]
Boom
